export default {
    controlBarButton: 18,
    timerDisplay: 15,
    benchTitle: 20,
    playerNumber: 15,
    playerTimerDisplays: 14,
    homePageButtons: 25,
    header: 60,
    formHeading: 40,
    formLabel: 20,
    formInputText: 15,
    formButton: 20,
    errorText: 20,
    summaryHeading: 40,
    summaryContent: 20,
};
